export const DeRiskOracle = [
	// ========== CRE Receiver ==========
	{
		inputs: [
			{ internalType: 'bytes', name: '', type: 'bytes' },
			{ internalType: 'bytes', name: 'report', type: 'bytes' },
		],
		name: 'onReport',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_riskScore', type: 'uint256' },
			{ internalType: 'uint256', name: '_tvl', type: 'uint256' },
			{ internalType: 'uint256', name: '_utilizationRate', type: 'uint256' },
			{ internalType: 'uint256', name: '_ethPrice', type: 'uint256' },
		],
		name: 'updateRiskData',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	// ========== Multi-Protocol ==========
	{
		inputs: [
			{ internalType: 'uint256', name: '_aaveScore', type: 'uint256' },
			{ internalType: 'uint256', name: '_compoundScore', type: 'uint256' },
			{ internalType: 'uint256', name: '_makerScore', type: 'uint256' },
		],
		name: 'updateProtocolScores',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: '_aaveTvl', type: 'uint256' },
			{ internalType: 'uint256', name: '_compoundTvl', type: 'uint256' },
			{ internalType: 'uint256', name: '_makerTvl', type: 'uint256' },
		],
		name: 'updateProtocolTvls',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	// ========== Contagion Analysis ==========
	{
		inputs: [
			{ internalType: 'uint256', name: '_contagionScore', type: 'uint256' },
			{ internalType: 'uint256', name: '_worstCaseLoss', type: 'uint256' },
		],
		name: 'updateContagionScore',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getContagionData',
		outputs: [
			{ internalType: 'uint256', name: '_contagionScore', type: 'uint256' },
			{ internalType: 'uint256', name: '_worstCaseLoss', type: 'uint256' },
			{ internalType: 'uint256', name: '_lastUpdated', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	// ========== Backtest Proofs ==========
	{
		inputs: [
			{ internalType: 'string', name: '_eventName', type: 'string' },
			{ internalType: 'uint256', name: '_alertLeadTimeHours', type: 'uint256' },
			{ internalType: 'uint256', name: '_peakRiskScore', type: 'uint256' },
			{ internalType: 'uint256', name: '_actualLossesUsd', type: 'uint256' },
			{ internalType: 'uint256', name: '_preventedLossesUsd', type: 'uint256' },
			{ internalType: 'uint256', name: '_effectivenessPercent', type: 'uint256' },
		],
		name: 'submitBacktestProof',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getBacktestCount',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		name: 'backtestResults',
		outputs: [
			{ internalType: 'string', name: 'eventName', type: 'string' },
			{ internalType: 'uint256', name: 'alertLeadTimeHours', type: 'uint256' },
			{ internalType: 'uint256', name: 'peakRiskScore', type: 'uint256' },
			{ internalType: 'uint256', name: 'actualLossesUsd', type: 'uint256' },
			{ internalType: 'uint256', name: 'preventedLossesUsd', type: 'uint256' },
			{ internalType: 'uint256', name: 'effectivenessPercent', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	// ========== Chainlink Automation ==========
	{
		inputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
		name: 'checkUpkeep',
		outputs: [
			{ internalType: 'bool', name: 'upkeepNeeded', type: 'bool' },
			{ internalType: 'bytes', name: 'performData', type: 'bytes' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
		name: 'performUpkeep',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	// ========== Admin ==========
	{
		inputs: [{ internalType: 'bool', name: '_active', type: 'bool' }],
		name: 'emergencyCircuitBreaker',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	// ========== View Functions ==========
	{
		inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
		name: 'supportsInterface',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'pure',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getRiskData',
		outputs: [
			{ internalType: 'uint256', name: '_riskScore', type: 'uint256' },
			{ internalType: 'bool', name: '_circuitBreakerActive', type: 'bool' },
			{ internalType: 'uint256', name: '_tvl', type: 'uint256' },
			{ internalType: 'uint256', name: '_utilizationRate', type: 'uint256' },
			{ internalType: 'uint256', name: '_ethPrice', type: 'uint256' },
			{ internalType: 'uint256', name: '_lastUpdateTimestamp', type: 'uint256' },
			{ internalType: 'uint256', name: '_updateCount', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getProtocolScores',
		outputs: [
			{ internalType: 'uint256', name: '_aave', type: 'uint256' },
			{ internalType: 'uint256', name: '_compound', type: 'uint256' },
			{ internalType: 'uint256', name: '_maker', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getProtocolTvls',
		outputs: [
			{ internalType: 'uint256', name: '_aaveTvl', type: 'uint256' },
			{ internalType: 'uint256', name: '_compoundTvl', type: 'uint256' },
			{ internalType: 'uint256', name: '_makerTvl', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getAggregateScore',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'isStale',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'needsUpdate',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'timeSinceUpdate',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'riskScore',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'circuitBreakerActive',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'tvl',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'utilizationRate',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'ethPrice',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'lastUpdateTimestamp',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'updateCount',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'aaveRiskScore',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'compoundRiskScore',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'makerRiskScore',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'aaveTvl',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'compoundTvl',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'makerTvl',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'contagionRiskScore',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'worstCaseSystemLoss',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'contagionLastUpdated',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'owner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'CIRCUIT_BREAKER_THRESHOLD',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'STALENESS_THRESHOLD',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'UPDATE_INTERVAL',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'AAVE_WEIGHT',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'COMPOUND_WEIGHT',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'MAKER_WEIGHT',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	// ========== Events ==========
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'uint256', name: 'score', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'tvl', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'ethPrice', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
		],
		name: 'RiskScoreUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'aaveScore', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'compoundScore', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'makerScore', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'aggregateScore', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
		],
		name: 'ProtocolScoresUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'score', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
		],
		name: 'CircuitBreakerTriggered',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'score', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
		],
		name: 'CircuitBreakerReset',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'lastUpdate', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'currentTime', type: 'uint256' },
		],
		name: 'StalenessAlert',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'contagionScore', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'worstCaseLoss', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
		],
		name: 'ContagionScoreUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
] as const
